/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as DevRouteImport } from './routes/dev'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DevTableApiPlaygroundRouteImport } from './routes/dev/table-api-playground'
import { Route as DevApiPlaygroundRouteImport } from './routes/dev/api-playground'
import { Route as DevAnalyticsRouteImport } from './routes/dev/analytics'
import { Route as DevAlertBannerRouteImport } from './routes/dev/alert-banner'
import { Route as DevAdminPlaygroundRouteImport } from './routes/dev/admin-playground'
import { Route as AuthWorkspaceRouteRouteImport } from './routes/_auth/workspace/route'
import { Route as AuthWorkspaceIndexRouteImport } from './routes/_auth/workspace/index'
import { Route as AuthWorkspaceWorkspaceIdIndexRouteImport } from './routes/_auth/workspace/$workspaceId.index'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const DevRoute = DevRouteImport.update({
  id: '/dev',
  path: '/dev',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DevTableApiPlaygroundRoute = DevTableApiPlaygroundRouteImport.update({
  id: '/table-api-playground',
  path: '/table-api-playground',
  getParentRoute: () => DevRoute,
} as any)
const DevApiPlaygroundRoute = DevApiPlaygroundRouteImport.update({
  id: '/api-playground',
  path: '/api-playground',
  getParentRoute: () => DevRoute,
} as any)
const DevAnalyticsRoute = DevAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => DevRoute,
} as any)
const DevAlertBannerRoute = DevAlertBannerRouteImport.update({
  id: '/alert-banner',
  path: '/alert-banner',
  getParentRoute: () => DevRoute,
} as any)
const DevAdminPlaygroundRoute = DevAdminPlaygroundRouteImport.update({
  id: '/admin-playground',
  path: '/admin-playground',
  getParentRoute: () => DevRoute,
} as any)
const AuthWorkspaceRouteRoute = AuthWorkspaceRouteRouteImport.update({
  id: '/workspace',
  path: '/workspace',
  getParentRoute: () => AuthRoute,
} as any)
const AuthWorkspaceIndexRoute = AuthWorkspaceIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthWorkspaceRouteRoute,
} as any)
const AuthWorkspaceWorkspaceIdIndexRoute =
  AuthWorkspaceWorkspaceIdIndexRouteImport.update({
    id: '/$workspaceId/',
    path: '/$workspaceId/',
    getParentRoute: () => AuthWorkspaceRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dev': typeof DevRouteWithChildren
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/workspace': typeof AuthWorkspaceRouteRouteWithChildren
  '/dev/admin-playground': typeof DevAdminPlaygroundRoute
  '/dev/alert-banner': typeof DevAlertBannerRoute
  '/dev/analytics': typeof DevAnalyticsRoute
  '/dev/api-playground': typeof DevApiPlaygroundRoute
  '/dev/table-api-playground': typeof DevTableApiPlaygroundRoute
  '/workspace/': typeof AuthWorkspaceIndexRoute
  '/workspace/$workspaceId/': typeof AuthWorkspaceWorkspaceIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dev': typeof DevRouteWithChildren
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/dev/admin-playground': typeof DevAdminPlaygroundRoute
  '/dev/alert-banner': typeof DevAlertBannerRoute
  '/dev/analytics': typeof DevAnalyticsRoute
  '/dev/api-playground': typeof DevApiPlaygroundRoute
  '/dev/table-api-playground': typeof DevTableApiPlaygroundRoute
  '/workspace': typeof AuthWorkspaceIndexRoute
  '/workspace/$workspaceId': typeof AuthWorkspaceWorkspaceIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/dev': typeof DevRouteWithChildren
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/_auth/workspace': typeof AuthWorkspaceRouteRouteWithChildren
  '/dev/admin-playground': typeof DevAdminPlaygroundRoute
  '/dev/alert-banner': typeof DevAlertBannerRoute
  '/dev/analytics': typeof DevAnalyticsRoute
  '/dev/api-playground': typeof DevApiPlaygroundRoute
  '/dev/table-api-playground': typeof DevTableApiPlaygroundRoute
  '/_auth/workspace/': typeof AuthWorkspaceIndexRoute
  '/_auth/workspace/$workspaceId/': typeof AuthWorkspaceWorkspaceIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dev'
    | '/signin'
    | '/signup'
    | '/workspace'
    | '/dev/admin-playground'
    | '/dev/alert-banner'
    | '/dev/analytics'
    | '/dev/api-playground'
    | '/dev/table-api-playground'
    | '/workspace/'
    | '/workspace/$workspaceId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dev'
    | '/signin'
    | '/signup'
    | '/dev/admin-playground'
    | '/dev/alert-banner'
    | '/dev/analytics'
    | '/dev/api-playground'
    | '/dev/table-api-playground'
    | '/workspace'
    | '/workspace/$workspaceId'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/dev'
    | '/signin'
    | '/signup'
    | '/_auth/workspace'
    | '/dev/admin-playground'
    | '/dev/alert-banner'
    | '/dev/analytics'
    | '/dev/api-playground'
    | '/dev/table-api-playground'
    | '/_auth/workspace/'
    | '/_auth/workspace/$workspaceId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  DevRoute: typeof DevRouteWithChildren
  SigninRoute: typeof SigninRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev': {
      id: '/dev'
      path: '/dev'
      fullPath: '/dev'
      preLoaderRoute: typeof DevRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev/table-api-playground': {
      id: '/dev/table-api-playground'
      path: '/table-api-playground'
      fullPath: '/dev/table-api-playground'
      preLoaderRoute: typeof DevTableApiPlaygroundRouteImport
      parentRoute: typeof DevRoute
    }
    '/dev/api-playground': {
      id: '/dev/api-playground'
      path: '/api-playground'
      fullPath: '/dev/api-playground'
      preLoaderRoute: typeof DevApiPlaygroundRouteImport
      parentRoute: typeof DevRoute
    }
    '/dev/analytics': {
      id: '/dev/analytics'
      path: '/analytics'
      fullPath: '/dev/analytics'
      preLoaderRoute: typeof DevAnalyticsRouteImport
      parentRoute: typeof DevRoute
    }
    '/dev/alert-banner': {
      id: '/dev/alert-banner'
      path: '/alert-banner'
      fullPath: '/dev/alert-banner'
      preLoaderRoute: typeof DevAlertBannerRouteImport
      parentRoute: typeof DevRoute
    }
    '/dev/admin-playground': {
      id: '/dev/admin-playground'
      path: '/admin-playground'
      fullPath: '/dev/admin-playground'
      preLoaderRoute: typeof DevAdminPlaygroundRouteImport
      parentRoute: typeof DevRoute
    }
    '/_auth/workspace': {
      id: '/_auth/workspace'
      path: '/workspace'
      fullPath: '/workspace'
      preLoaderRoute: typeof AuthWorkspaceRouteRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/workspace/': {
      id: '/_auth/workspace/'
      path: '/'
      fullPath: '/workspace/'
      preLoaderRoute: typeof AuthWorkspaceIndexRouteImport
      parentRoute: typeof AuthWorkspaceRouteRoute
    }
    '/_auth/workspace/$workspaceId/': {
      id: '/_auth/workspace/$workspaceId/'
      path: '/$workspaceId'
      fullPath: '/workspace/$workspaceId/'
      preLoaderRoute: typeof AuthWorkspaceWorkspaceIdIndexRouteImport
      parentRoute: typeof AuthWorkspaceRouteRoute
    }
  }
}

interface AuthWorkspaceRouteRouteChildren {
  AuthWorkspaceIndexRoute: typeof AuthWorkspaceIndexRoute
  AuthWorkspaceWorkspaceIdIndexRoute: typeof AuthWorkspaceWorkspaceIdIndexRoute
}

const AuthWorkspaceRouteRouteChildren: AuthWorkspaceRouteRouteChildren = {
  AuthWorkspaceIndexRoute: AuthWorkspaceIndexRoute,
  AuthWorkspaceWorkspaceIdIndexRoute: AuthWorkspaceWorkspaceIdIndexRoute,
}

const AuthWorkspaceRouteRouteWithChildren =
  AuthWorkspaceRouteRoute._addFileChildren(AuthWorkspaceRouteRouteChildren)

interface AuthRouteChildren {
  AuthWorkspaceRouteRoute: typeof AuthWorkspaceRouteRouteWithChildren
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthWorkspaceRouteRoute: AuthWorkspaceRouteRouteWithChildren,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface DevRouteChildren {
  DevAdminPlaygroundRoute: typeof DevAdminPlaygroundRoute
  DevAlertBannerRoute: typeof DevAlertBannerRoute
  DevAnalyticsRoute: typeof DevAnalyticsRoute
  DevApiPlaygroundRoute: typeof DevApiPlaygroundRoute
  DevTableApiPlaygroundRoute: typeof DevTableApiPlaygroundRoute
}

const DevRouteChildren: DevRouteChildren = {
  DevAdminPlaygroundRoute: DevAdminPlaygroundRoute,
  DevAlertBannerRoute: DevAlertBannerRoute,
  DevAnalyticsRoute: DevAnalyticsRoute,
  DevApiPlaygroundRoute: DevApiPlaygroundRoute,
  DevTableApiPlaygroundRoute: DevTableApiPlaygroundRoute,
}

const DevRouteWithChildren = DevRoute._addFileChildren(DevRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  DevRoute: DevRouteWithChildren,
  SigninRoute: SigninRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
