/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ExpressionRouteImport } from './routes/expression'
import { Route as IndexRouteImport } from './routes/index'

const ExpressionRoute = ExpressionRouteImport.update({
  id: '/expression',
  path: '/expression',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/expression': typeof ExpressionRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/expression': typeof ExpressionRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/expression': typeof ExpressionRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/expression'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/expression'
  id: '__root__' | '/' | '/expression'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ExpressionRoute: typeof ExpressionRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/expression': {
      id: '/expression'
      path: '/expression'
      fullPath: '/expression'
      preLoaderRoute: typeof ExpressionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ExpressionRoute: ExpressionRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
